FAD-60 selection tool user toggle
weavik/free-artist-dao pull request #12
Opened 2022-09-07 14:41 UTC by sachasmart-weavik

### Description

> User Toggle Switch
Figma File: https://www.figma.com/file/g7Edk2JCOMLpRAw9v8NJ4c/FA-Product-Wireframe---working-file?node-id=94%3A12407
### Checklist

[FAD-60]

- [ ] `CHANGELOG` has been update
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/98773781/188906809-03e445d7-dd1c-4910-b4c9-7c59fe848115.gif)
d (_if appropriate_)
- [ ] Environment variables updated (_if appropriate_)

2022-09-07 21:02 UTC, v1n33th approved these changes
Awesome and great transitions. Just a minor suggestion with naming

2022-09-07 21:26 UTC, sachasmart-weavik commented on packages/client3/components/design-system/toggle/toggle.tsx
> +  };
How about: 
```
states: {
  selectedState: string;
   state1: string;
   state2:string;
}
```

I'll defer to the group @luansievers. Personally, I like everything nested together.

2022-09-09 12:58 UTC, luansievers requested changes
update your branch and check the classes again please.
also, add package-lock.json again lol

2022-09-09 12:58 UTC, luansievers commented on packages/client3/tailwind.config.js
> +          accent5: "#343E3B",
you might need to update your branch with the main

2022-09-09 17:12 UTC, sachasmart-weavik commented on packages/client3/components/design-system/toggle/toggle.tsx
> +  };
Went with this.

2022-09-09 17:16 UTC, sachasmart-weavik commented
I have no idea why the package-lock.json was deleted from `packages/client3`. I have attached a video to show that it is there...


![ezgif com-gif-maker-3](https://user-images.githubusercontent.com/98773781/189407923-f0733bef-a29c-4727-b0f6-7dd82ce0fe71.gif)

2022-09-12 10:12 UTC, luansievers requested changes

2022-09-12 10:12 UTC, luansievers commented on packages/client3/components/design-system/toggle/toggle.stories.tsx
> +    state2: "Artist",
in my opinion, this is not quite clear what state is active, I mean

`state1, state2, selectedState: true,` what is selected?

myabe change the `selectedState` to `isState1Selected`

2022-09-12 13:11 UTC, luansievers approved these changes

2022-09-12 13:13 UTC, merged