[FAD-70]
weavik/free-artist-dao pull request #13
Opened 2022-09-07 19:07 UTC by v1n33th

### Description

Added dashboard total component and related files

`TODO`: Integrate new button design after merge

- [ ] `CHANGELOG` has been updated (_if appropriate_)
- [ ] Environment variables updated (_if appropriate_)

2022-09-09 19:15 UTC, v1n33th commented
Images

With Button
![Screen Shot 2022-09-09 at 3 14 56 PM](https://user-images.githubusercontent.com/36981665/189426949-605c0acc-45c7-4088-bc1c-41f15bfc0fd5.png)

Without Button
![Screen Shot 2022-09-09 at 3 15 27 PM](https://user-images.githubusercontent.com/36981665/189427033-74d7c709-52ef-4526-9771-a2fcaa42702a.png)

2022-09-12 11:22 UTC, luansievers requested changes

2022-09-12 11:22 UTC, luansievers commented on packages/client3/components/dashboard/total/dashboard-total.tsx
> +          ${totalRaised ?? 0}
I think you can format those values with `formatCrypto`

2022-09-12 11:22 UTC, luansievers commented on packages/client3/components/dashboard/total/dashboard-total.tsx
> +          ${totalEarned ?? 0}
Same here

2022-09-12 13:27 UTC, sachasmart-weavik approved these changes
Nice man. 

I was OCD and checked the image, tinyPNG'd it and pushed it.

2022-09-13 12:28 UTC, luansievers approved these changes

2022-09-13 13:59 UTC, merged