[FAD-5] IPFS
weavik/free-artist-dao pull request #26
Opened 2022-09-16 22:18 UTC by sachasmart-weavik

### Description

> Containerized IPFS and file uploader. 
Read the packages/ipfs/README.md and I can demo it on Monday before you two look at the PR. 

### Checklist

- [ ] `CHANGELOG` has been updated (_if appropriate_)
- [ ] Environment variables updated (_if appropriate_)

2022-09-21 17:59 UTC, v1n33th requested changes
Awesome...Some minor suggestions

2022-09-21 17:59 UTC, v1n33th commented on packages/client3/components/design-system/file-upload/file-upload.tsx
> +};
Would suggest converting the file reader method to [promise](https://simon-schraeder.de/posts/filereader-async/) and then extracting the addFile to a utils/services class to aid reusability. Also would suggest using camelCase for function names

2022-09-21 17:59 UTC, v1n33th commented on packages/client3/components/design-system/file-upload/file-upload.tsx
> +    }, []);
Is this useCallback function called as it's not assigned to any variables to use?

2022-09-21 17:59 UTC, v1n33th commented on packages/client3/ipfs/README.md
> +   4. Magic.
lol

2022-09-21 17:59 UTC, v1n33th commented on packages/client3/components/design-system/file-upload/file-upload.tsx
> +    const [files, setFiles] = useState([] as any);
Does the component support multiple files?

2022-09-26 18:51 UTC, v1n33th approved these changes
Just some minor suggestions

2022-09-26 18:51 UTC, v1n33th commented on packages/client3/components/design-system/file-upload/file-upload.tsx
> +    });
This useEffect runs on every render as it has no dependency. Is this intended?

2022-09-26 18:51 UTC, v1n33th commented on packages/client3/components/design-system/file-upload/file-upload.tsx
> +      () => () => {
Is this by mistake or required?

2022-09-26 18:51 UTC, v1n33th commented on packages/client3/ipfs/utils/services/file-upload.ts
> +    return await fileReader.readAsArrayBuffer(fileToUpload);
Not sure. But i don't think `readAsArrayBuffer` is a async function and can be waited. Maybe promisify `readAsArrayBuffer` method and use await

2022-09-27 01:34 UTC, sachasmart-weavik commented
Closing due to the changes when implementing [[FAD-108] ](https://github.com/weavik/free-artist-dao/pull/33)

2022-09-27 01:34 UTC, closed without merging